service:
  name: travis-publish

provider:
  name: cloudflare

config:
  accountId: ${env:ACCOUNT_ID}
  zoneId: ${env:ZONE_ID}

plugins:
  - serverless-cloudflare-workers

functions:
  deploy-from-travis:
    name: travis-deployed-worker
    script: worker

